project:
  type: website
  output-dir: docs
  preview: 
      browser: true
      port: 5500

website:
  title: "Anagha Patil"
  favicon: content/AnaghaPatil.png
  twitter-card: true
  page-footer: 
    left: Copyright 2024, Anagha Patil
    right: This website was made with &#10084; using <a href="https://quarto.org/">Quarto</a>.
  navbar:
    right:
      - experience.qmd
      - projects.qmd
      - pubs.qmd
      - teaching.qmd
      - text: Resume
        href: resumes/AnaghaPatil_Resume.pdf
format:
  html:
    # link-external-icon: true
    # link-external-newwindow: true
    from: markdown+emoji
    theme: flatly
    css: styles.scss